const menuList = [
    {
        id: "1",
        path: "/main/parameter",
        title: "管理",
        children: [
            {
                id: "1-1",
                icon: "",
                title: "持仓限额管理",
                path: "/main/parameter/positionLimit",
            },
            {
                id: "1-2",
                icon: "",
                title: "期权信息管理",
                path: "/main/parameter/optionInfo",
            },
            {
                id: "1-3",
                icon: "",
                title: "资金信息管理",
                path: "/main/parameter/assetInfo",
            },
            {
                id: "1-4",
                icon: "",
                title: "资金流水",
                path: "/main/parameter/capitalFlow",
            },
        ],
    },
    {
        id: "2",
        path: "/main/updown",
        title: "数据导入导出",
        children: [
            {
                id: "2-31",
                icon: "",
                title: "全部信息",
                path: "/main/updown/allInfo",
            },
            {
                id: "2-1",
                icon: "",
                title: "用户信息",
                path: "/main/updown/userInfo",
            },
            {
                id: "2-2",
                icon: "",
                title: "资金信息",
                path: "/main/updown/assetInfo",
            },
            {
                id: "2-3",
                icon: "",
                title: "股东信息",
                path: "/main/updown/stockHolder",
            },
            {
                id: "2-4",
                icon: "",
                title: "用户网关",
                path: "/main/updown/userPbuGwConfig",
            },
            {
                id: "2-5",
                icon: "",
                title: "证券信息",
                path: "/main/updown/security",
            },
            {
                id: "2-6",
                icon: "",
                title: "期权信息",
                path: "/main/updown/optionInfo",
            },
            {
                id: "2-7",
                icon: "",
                title: "用户配置",
                path: "/main/updown/userConfig",
            },
            {
                id: "2-8",
                icon: "",
                title: "交易时间组",
                path: "/main/updown/tradeTime",
            },
            {
                id: "2-9",
                icon: "",
                title: "持仓限额",
                path: "/main/updown/positionLimit",
            },
            {
                id: "2-10",
                icon: "",
                title: "期权持仓",
                path: "/main/updown/optionPosition",
            },
            {
                id: "2-11",
                icon: "",
                title: "交易网关",
                path: "/main/updown/gwConfig",
            },
            {
                id: "2-12",
                icon: "",
                title: "费率配置",
                path: "/main/updown/feeRateConfig",
            },
            {
                id: "2-13",
                icon: "",
                title: "组合持仓策略",
                path: "/main/updown/strategyPosition",
            },
            {
                id: "2-13",
                icon: "",
                title: "组合持仓配置",
                path: "/main/updown/strategyConfig",
            },
        ],
    },
    // {
    //     id: "1",
    //     path: "/main/chart",
    //     title: "统计图",
    //     children: [
    //         {
    //             id: "2-1",
    //             icon: "",
    //             title: "在线人数",
    //             path: "/main/chart/onlineUser",
    //         },
    //         {
    //             id: "2-2",
    //             icon: "",
    //             title: "下单统计",
    //             path: "/main/chart/order",
    //         },
    //         {
    //             id: "2-3",
    //             icon: "",
    //             title: "撤单统计",
    //             path: "/main/chart/orderCancel",
    //         },
    //         {
    //             id: "2-4",
    //             icon: "",
    //             title: "成交统计",
    //             path: "/main/chart/orderDeal",
    //         },
    //         {
    //             id: "2-5",
    //             icon: "",
    //             title: "cpu使用率",
    //             path: "/main/chart/cpu",
    //         },
    //         {
    //             id: "2-3",
    //             icon: "",
    //             title: "内存使用率",
    //             path: "/main/chart/ram",
    //         },
    //         {
    //             id: "2-4",
    //             icon: "",
    //             title: "硬盘使用率",
    //             path: "/main/chart/disk",
    //         },
    //         {
    //             id: "2-5",
    //             icon: "",
    //             title: "网络带宽",
    //             path: "/main/chart/network",
    //         },
    //     ],
    // },
];
export default menuList;
