const menuList = [
    {
        id: "1",
        path: "/main/parameter",
        title: "管理",
        children: [
            {
                id: "1-1",
                icon: "",
                title: "持仓限额",
                path: "/main/parameter/positionLimit",
            },
            {
                id: "1-2",
                icon: "",
                title: "期权信息",
                path: "/main/parameter/optionInfo",
            },
            {
                id: "1-3",
                icon: "",
                title: "资金信息",
                path: "/main/parameter/assetInfo",
            },
            {
                id: "1-4",
                icon: "",
                title: "资金流水",
                path: "/main/parameter/capitalFlow",
            },
            {
                id: "1-5",
                icon: "",
                title: "期权持仓",
                path: "/main/parameter/optionPositionQuery",
            },
            {
                id: "1-106",
                icon: "",
                title: "行权流水",
                path: "/main/parameter/exerciseRecordQuery",
            },
            {
                id: "1-6",
                icon: "",
                title: "组合策略流水",
                path: "/main/parameter/strategyPositionQuery",
            },
            {
                id: "1-7",
                icon: "",
                title: "订单",
                path: "/main/parameter/newOrderQuery",
            },
            {
                id: "1-17",
                icon: "",
                title: "撤单",
                path: "/main/parameter/cancelOrderQuery",
            },
            {
                id: "1-8",
                icon: "",
                title: "备兑",
                path: "/main/parameter/coverQuery",
            },
            {
                id: "1-9",
                icon: "",
                title: "期权持仓流水",
                path: "/main/parameter/positionLogQuery",
            },
            {
                id: "1-18",
                icon: "",
                title: "成交回执",
                path: "/main/parameter/execReport",
            },
            {
                id: "1-11",
                icon: "",
                title: "用户配置",
                path: "/main/parameter/userConfigQuery",
            },
            {
                id: "1-12",
                icon: "",
                title: "股东信息",
                path: "/main/parameter/stockHolderQuery",
            },
            {
                id: "1-13",
                icon: "",
                title: "证券信息",
                path: "/main/parameter/securityQuery",
            },
            {
                id: "1-14",
                icon: "",
                title: "交易网关",
                path: "/main/parameter/gwConfigQuery",
            },
            {
                id: "1-15",
                icon: "",
                title: "交易时间",
                path: "/main/parameter/tradeTimeQuery",
            },
            {
                id: "1-16",
                icon: "",
                title: "用户网关",
                path: "/main/parameter/userPbuGwConfigQuery",
            },
        ],
    },
    {
        id: "2",
        path: "/main/updown",
        title: "数据导入导出",
        children: [
            {
                id: "2-31",
                icon: "",
                title: "全部信息",
                path: "/main/updown/allInfo",
            },
            {
                id: "2-1",
                icon: "",
                title: "用户信息",
                path: "/main/updown/userInfo",
            },
            {
                id: "2-2",
                icon: "",
                title: "资金信息",
                path: "/main/updown/assetInfo",
            },
            {
                id: "2-3",
                icon: "",
                title: "股东信息",
                path: "/main/updown/stockHolder",
            },
            {
                id: "2-4",
                icon: "",
                title: "用户网关",
                path: "/main/updown/userPbuGwConfig",
            },
            {
                id: "2-5",
                icon: "",
                title: "证券信息",
                path: "/main/updown/security",
            },
            {
                id: "2-6",
                icon: "",
                title: "期权信息",
                path: "/main/updown/optionInfo",
            },
            {
                id: "2-7",
                icon: "",
                title: "用户配置",
                path: "/main/updown/userConfig",
            },
            {
                id: "2-8",
                icon: "",
                title: "交易时间组",
                path: "/main/updown/tradeTime",
            },
            {
                id: "2-9",
                icon: "",
                title: "持仓限额",
                path: "/main/updown/positionLimit",
            },
            {
                id: "2-10",
                icon: "",
                title: "期权持仓",
                path: "/main/updown/optionPosition",
            },
            {
                id: "2-11",
                icon: "",
                title: "交易网关",
                path: "/main/updown/gwConfig",
            },
            {
                id: "2-12",
                icon: "",
                title: "费率配置",
                path: "/main/updown/feeRateConfig",
            },
            {
                id: "2-13",
                icon: "",
                title: "组合持仓策略",
                path: "/main/updown/strategyPosition",
            },
            {
                id: "2-13",
                icon: "",
                title: "组合持仓配置",
                path: "/main/updown/strategyConfig",
            },
            {
                id: "2-14",
                icon: "",
                title: "合约品种持仓",
                path: "/main/updown/contractVarietyPos",
            },
        ],
    },
    {
        id: "3",
        path: "/main/chart",
        title: "统计图",
        children: [
            {
                id: "3-1",
                icon: "",
                title: "在线人数",
                path: "/main/chart/onlineUser",
            },
            // {
            //     id: "3-2",
            //     icon: "",
            //     title: "下单统计",
            //     path: "/main/chart/order",
            // },
            // {
            //     id: "3-3",
            //     icon: "",
            //     title: "撤单统计",
            //     path: "/main/chart/orderCancel",
            // },
            // {
            //     id: "3-4",
            //     icon: "",
            //     title: "成交统计",
            //     path: "/main/chart/orderDeal",
            // },
            {
                id: "3-5",
                icon: "",
                title: "cpu使用率",
                path: "/main/chart/cpu",
            },
            {
                id: "3-6",
                icon: "",
                title: "内存使用率",
                path: "/main/chart/ram",
            },
            {
                id: "3-7",
                icon: "",
                title: "硬盘使用率",
                path: "/main/chart/disk",
            },
            // {
            //     id: "3-8",
            //     icon: "",
            //     title: "网络带宽",
            //     path: "/main/chart/network",
            // },
        ],
    },
];
export default menuList;
